apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.6/git-clone.yaml
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/terraform-cli/0.2/terraform-cli.yaml
- https://api.hub.tekton.dev/v1/resource/tekton/task/kaniko/0.6/raw
- terraform.yaml
secretGenerator:
- name: kubeconfig
  files:
  - ./secretFile/harvester.yaml
- name: terraform-secret
  literals:
  - FRUIT=apple
  - VEGETABLE=carrot
  - KUBECONFIG=/kubeconfig/harvester.yaml
generatorOptions:
  disableNameSuffixHash: true
