apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "./pipelines"
- "./tasks"
secretGenerator:
- name: kubeconfig
  files:
  - ./secretFile/harvester.yaml
- name: terraform-secret
  literals:
  - KUBECONFIG=/kubeconfig/harvester.yaml
generatorOptions:
  disableNameSuffixHash: true
