apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml
- https://raw.githubusercontent.com/tektoncd/operator/main/config/crs/kubernetes/config/all/operator_v1alpha1_config_cr.yaml
- https://storage.googleapis.com/tekton-releases/dashboard/latest/release.yaml
- dashboard-ingress.yaml
- "./pipelines"
- "./tasks"
secretGenerator:
- name: kubeconfig
  files:
  - ./secretFile/harvester.yaml
- name: nexus-dockerconfig
  files:
  - ./secretFile/config.json
- name: terraform-secret
  literals:
  - KUBECONFIG=/kubeconfig/harvester.yaml
generatorOptions:
  disableNameSuffixHash: true
