apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: terraform-automate-
spec:
  pipelineRef:
    name: terraform-automate
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://git.192-168-100-200.year.date/bolinz/fluxcd.git
  - name: terraform-secret
    value: terraform-secret
