apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: terraform-automate
spec:
  description: "This pipeline clones a git repo, builds a Docker image with Kaniko and\npushes it to a registry    \n"
  params:
  - name: repo-url
    type: string
  - name: terraform-secret
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: terraform
    runAfter: ["fetch-source"]
    taskRef:
      name: terraform-cli
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: ARGS
      value:
      - "plan"
    - name: terraform-secret
      value: $(params.terraform-secret)
